name: Image Processing Pipeline

on:
  push:
    paths:
      - 'decryption/input/**'  # Trigger when a file is pushed to the 'decryption/input/' directory

jobs:
  process-images:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v4  # Updated to v4

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Run script1.py to process the uploaded image
    - name: Run script1.py
      run: python scripts/script1.py

    # Step 5: Run script2.py to further process the data
    - name: Run script2.py
      run: python scripts/script2.py

    # Step 6: Run script3.py to merge data and generate final output
    - name: Run script3.py
      run: python scripts/script3.py

    # Step 7: List files in the input directory before deletion
    - name: List files before deletion
      run: ls -la ./decryption/input

    # Step 8: Delete uploaded PNG files using Python
    - name: Delete Uploaded PNGs with Python
      run: |
        python -c "
import os
import glob
png_files = glob.glob('./decryption/input/*.png')
for file_path in png_files:
    os.remove(file_path)
print('PNG files deleted successfully.')
        "

    # Step 9: List files in the input directory after deletion
    - name: List files after deletion
      run: ls -la ./decryption/input

    # Step 10: Upload the final processed output as an artifact
    - name: Upload Final Output
      uses: actions/upload-artifact@v4
      with:
        name: processed-results
        path: './process/merged_data_with_metadata.csv'
