name: Image Processing Pipeline

on:
  push:
    paths:
      - 'decryption/input/**'  # Trigger when a file is pushed to 'decryption/input/'

jobs:
  process-images:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow pushing changes to the repository

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # Ensure Git credentials are available

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Create the process directory (if it doesn't exist)
    - name: Create process directory
      run: mkdir -p decryption/process/

    # Step 5: Run script1.py
    - name: Run script1.py
      run: python scripts/script1.py

    # Step 6: Run script2.py
    - name: Run script2.py
      run: python scripts/script2.py

    # Step 7: Run script3.py
    - name: Run script3.py
      run: python scripts/script3.py

    # Step 8: Check if the output file exists before committing
    - name: Verify output file exists
      run: |
      if [ ! -f "decryption/process/merged_data_with_metadata.csv" ]; then
      echo "Output file not found!"
      exit 1
    fi

    # Step 9: Commit the final processed output to the repository
    - name: Commit final output
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add decryption/process/merged_data_with_metadata.csv
        git commit -m "Add processed result"
        git push

    # Step 10: Run script4.py to delete PNG files and push changes
    - name: Delete Uploaded PNGs and Push Changes
      run: python scripts/script4.py
