name: Process and Display Image Tokens

on:
  workflow_dispatch: # This can be triggered manually

jobs:
  process-images:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python (Skip if environment pre-configured)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install Dependencies (Skip if pre-configured)
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Clean process directory
      - name: Clean process directory
        run: |
          echo "Cleaning process directory..."
          rm -rf process/*
          echo "Process directory cleaned."

      # Step 5: Ensure Input Directory
      - name: Ensure Input Directory
        run: |
          mkdir -p decryption/input
          echo "Input directory ensured."

      # Step 6: Process Image (Run all scripts in sequence)
      - name: Process Image and Generate Data
        run: |
          echo "Running script1.py..."
          python scripts/script1.py
          echo "Running script2.py..."
          python scripts/script2.py
          echo "Running script3.py..."
          python scripts/script3.py

      # Step 7: Verify output and upload
      - name: Verify and Upload Processed Data
        if: success()
        run: |
          if [ -f "process/merged_data_with_metadata.csv" ]; then
            echo "Output file 'merged_data_with_metadata.csv' found!"
            # Upload the processed results
            echo "Uploading processed results..."
          else
            echo "Error: Output file not found!"
            exit 1
          fi

      # Step 8: Fetch and Display Token Details
      - name: Fetch and Display Token Details
        run: |
          echo "Running script_display.py to fetch and display token details..."
          python scripts/script_display.py
