name: Image Processing Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'decryption/input/**'

jobs:
  process-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Reduced permissions since we're not pushing

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache virtual environment
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install Dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run processing scripts
      run: |
        source .venv/bin/activate
        python scripts/script1.py
        python scripts/script2.py
        python scripts/script3.py

    - name: Verify output file exists
      run: |
        if [ ! -f "process/merged_data_with_metadata.csv" ]; then
          echo "Error: Output file not found!"
          exit 1
        else
          echo "Output file 'process/merged_data_with_metadata.csv' found!"
        fi

    - name: Upload processed result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: processed-results-${{ github.sha }}
        path: process/merged_data_with_metadata.csv

    # Optional: Remove if not needed
    - name: Clean up input files
      run: |
        rm -rf decryption/input/*

