name: Image Processing Pipeline

on:
  push:
    paths:
      - 'decryption/input/**'  # Trigger when a file is pushed to the 'decryption/input/' directory

jobs:
  process-images:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v4  # Updated to v4

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Run script1.py to process the uploaded image
    - name: Run script1.py
      run: python scripts/script1.py

    # Step 5: Run script2.py to further process the data
    - name: Run script2.py
      run: python scripts/script2.py

    # Step 6: Run script3.py to merge data and generate final output
    - name: Run script3.py
      run: python scripts/script3.py

    # Step 7: List files in the process directory (for debugging)
    - name: List files in process directory
      run: ls -la ./process

    # Step 8: Upload the final processed output as an artifact
    - name: Upload Final Output
      uses: actions/upload-artifact@v4
      with:
        name: processed-results
        path: './process/merged_data_with_metadata.csv'

    # Step 9: Delete uploaded PNG files from input directory
    - name: Delete Uploaded PNGs
      run: |
        rm -f ./decryption/input/*.png
        echo "Uploaded PNG files deleted."
