name: Image Processing Pipeline

on:
  # Trigger on push to main branch or when a file is pushed to the input directory
  push:
    branches:
      - main
    paths:
      - 'decryption/input/**'  # Trigger when a file is pushed to 'decryption/input/'

jobs:
  process-images:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow pushing changes to the repository

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # Ensure Git credentials are available

    # Step 2: Cache pip dependencies
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Step 3: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Step 4: Install dependencies (only if not cached)
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Step 5: Run process.py to delete and recreate the 'process' directory in the repository root
    - name: Reset process directory
      run: python scripts/process.py  # This script will delete and recreate the process directory in the root

    # Step 6: Run script4.py to delete all files and the input directory
    - name: Delete input files and directory
      run: python scripts/script4.py  # This runs your updated script to delete all files and the input directory

    # Step 7: Ensure the input directory exists before running any scripts
    - name: Create input directory if missing
      run: mkdir -p ${{ github.workspace }}/decryption/input  # Create the input directory if it doesn't exist

    # Step 8: Debugging - List files in input directory to confirm it's empty
    - name: Check input directory for PNGs after deletion
      run: |
        echo "Checking input directory for PNGs after deletion:"
        ls -la ${{ github.workspace }}/decryption/input/

    # Step 9: Run the main processing scripts (No delay)
    - name: Run processing scripts
      run: |
        python scripts/script1.py
        python scripts/script2.py
        python scripts/script3.py

    # Step 10: Verify if the output file exists using an absolute path
    - name: Verify output file exists
      run: |
        if [ ! -f "${{ github.workspace }}/process/merged_data_with_metadata.csv" ]; then
          echo "Output file not found!"
          exit 1
        else
          echo "Output file found!"
        fi

    # Step 11: Pull from remote, commit, and push processed results if changes exist
    - name: Pull, commit and push processed result
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git pull origin main || true  # Pull the latest changes from the remote repository
        git add process/merged_data_with_metadata.csv
        git diff --cached --quiet || git commit -m "Add processed result for ${{ github.sha }}"
        git push

    # Step 12: Upload the artifact with a unique name including commit SHA
    - name: Upload processed result as artifact
      uses: actions/upload-artifact@v4
      with:
        name: processed-results-${{ github.sha }}
        path: process/merged_data_with_metadata.csv

    # Step 13: Clean up process directory
    - name: Clean up process directory
      run: rm -rf ${{ github.workspace }}/process/*
