name: Image Processing Pipeline

on:
  push:
    paths:
      - 'decryption/input/**'  # Trigger when a file is pushed to 'decryption/input/'

jobs:
  process-images:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow pushing changes to the repository

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # Ensure Git credentials are available

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Run scriptx.py to clean up specific old CSV files
    - name: Run scriptx.py (Clean up specific old CSVs)
      run: python scripts/scriptx.py  # Running the custom clean-up script

    # Step 5: Run script1.py
    - name: Run script1.py
      run: python scripts/script1.py

    # Step 6: Run script2.py
    - name: Run script2.py
      run: python scripts/script2.py

    # Step 7: Run script3.py
    - name: Run script3.py
      run: python scripts/script3.py

    # Step 8: Verify if the output file exists
    - name: Verify output file exists
      run: |
        if [ ! -f "process/merged_data_with_metadata.csv" ]; then
          echo "Output file not found!"
          exit 1
        else
          echo "Output file found!"
        fi

    # Step 9: Stage and commit if changes exist
    - name: Stage and commit if changes exist
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add process/*.csv || true
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          git commit -m "Add processed result"
          git push
        fi

    # Step 10: Upload the artifact (merged_data_with_metadata.csv) using v4
    - name: Upload processed result as artifact
      uses: actions/upload-artifact@v4  # Updated to v4 to avoid deprecation
      with:
        name: processed-results
        path: process/merged_data_with_metadata.csv

    # Step 11: Run script4.py to delete PNG files
    - name: Delete Uploaded PNGs
      run: |
        python scripts/script4.py

    # Step 12: Clean up
    - name:
