name: Image Processing Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'decryption/input/**'

jobs:
  process-images:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Create input directory if missing
      run: mkdir -p decryption/input

    - name: Check input directory for PNGs
      run: |
        echo "Checking input directory for PNGs:"
        ls -la decryption/input/

    - name: Run processing scripts
      run: |
        python scripts/script1.py
        python scripts/script2.py
        python scripts/script3.py

    - name: Verify if the output file exists
      id: check-output
      run: |
        if [ -f "process/merged_data_with_metadata.csv" ]; then
          echo "Output file found."
          echo "file_exists=true" >> $GITHUB_ENV
        else
          echo "Output file not found."
          echo "file_exists=false" >> $GITHUB_ENV
          exit 0

    - name: Commit and force push processed result
      if: env.file_exists == 'true'
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add process/merged_data_with_metadata.csv
        git commit -m "Add processed result for ${{ github.sha }}"
        git push --force

    - name: Upload processed result as artifact
      if: env.file_exists == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: processed-results-${{ github.sha }}
        path: process/merged_data_with_metadata.csv

    - name: Clean up process directory
      run: rm -rf process/*

    - name: Delete input files and directory after processing
      run: python scripts/script4.py
