name: Image Processing Pipeline

on:
  push:
    paths:
      - 'decryption/input/**'  # Trigger when a file is pushed to 'decryption/input/'

jobs:
  process-images:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow pushing changes to the repository

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # Ensure Git credentials are available

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Run script1.py
    - name: Run script1.py
      run: python scripts/script1.py

    # Step 5: Run script2.py
    - name: Run script2.py
      run: python scripts/script2.py

    # Step 6: Run script3.py
    - name: Run script3.py
      run: python scripts/script3.py

    # Step 7: Upload the final processed output as an artifact
    - name: Upload Final Output
      uses: actions/upload-artifact@v4
      with:
        name: processed-results
        path: './process/merged_data_with_metadata.csv'

    # Step 8: Run script4.py to delete PNG files and push changes
    - name: Delete Uploaded PNGs and Push Changes
      run: python scripts/script4.py
