name: Image Processing Pipeline

on:
  push:
    paths:
      - 'decryption/input/**'  # Trigger the workflow when a file is pushed to 'decryption/input' directory

jobs:
  process-images:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Run script0.py from the correct path (scripts/ directory)
    - name: Run script0.py
      run: python scripts/script0.py  # Correct the path

    # Step 5: Run script1.py from the correct path
    - name: Run script1.py
      run: python scripts/script1.py  # Correct the path

    # Step 6: Run script2.py from the correct path
    - name: Run script2.py
      run: python scripts/script2.py  # Correct the path

    # Step 7: Run script3.py from the correct path
    - name: Run script3.py
      run: python scripts/script3.py  # Correct the path

    # Step 8: Upload the final processed output as an artifact
    - name: Upload Final Output
      uses: actions/upload-artifact@v3
      with:
        name: processed-results
        path: './process/merged_data_with_metadata.csv'
